"""init

Revision ID: d63fb4933bf5
Revises: 
Create Date: 2026-09-15 23:42:10.253707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('lat', sa.Double(), nullable=False),
    sa.Column('lng', sa.Double(), nullable=False),
    sa.Column('altitude', sa.Double(), nullable=True),
    sa.Column('status', sa.Text(), server_default='online', nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('firmware_version', sa.Text(), nullable=True),
    sa.Column('device_token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token_hash'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tracked_imsis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('imsi_hash', sa.Text(), nullable=False),
    sa.Column('imsi_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Text(), server_default='low', nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imsi_hash')
    )
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('imsi_hash', sa.Text(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), server_default='info', nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_resolved', 'alerts', ['resolved'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_table('imsi_observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('imsi_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('imsi_hash', sa.Text(), nullable=False),
    sa.Column('mcc', sa.Text(), nullable=True),
    sa.Column('mnc', sa.Text(), nullable=True),
    sa.Column('lac', sa.Integer(), nullable=True),
    sa.Column('cell_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('operator', sa.Text(), nullable=True),
    sa.Column('signal_dbm', sa.Integer(), nullable=True),
    sa.Column('snr_db', sa.Integer(), nullable=True),
    sa.Column('arfcn', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Double(), nullable=True),
    sa.Column('tmsi1', sa.Text(), nullable=True),
    sa.Column('tmsi2', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_imsi_observations_device_id_observed_at', 'imsi_observations', ['device_id', 'observed_at'], unique=False)
    op.create_index('ix_imsi_observations_imsi_hash', 'imsi_observations', ['imsi_hash'], unique=False)
    op.create_index('ix_imsi_observations_observed_at', 'imsi_observations', ['observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_imsi_observations_observed_at', table_name='imsi_observations')
    op.drop_index('ix_imsi_observations_imsi_hash', table_name='imsi_observations')
    op.drop_index('ix_imsi_observations_device_id_observed_at', table_name='imsi_observations')
    op.drop_table('imsi_observations')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index('ix_alerts_resolved', table_name='alerts')
    op.drop_index('ix_alerts_created_at', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('tracked_imsis')
    op.drop_table('devices')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
