/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as AiInvestigatorRouteImport } from './routes/ai-investigator'
import { Route as IndexRouteImport } from './routes/index'

const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInvestigatorRoute = AiInvestigatorRouteImport.update({
  id: '/ai-investigator',
  path: '/ai-investigator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-investigator': typeof AiInvestigatorRoute
  '/devices': typeof DevicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-investigator': typeof AiInvestigatorRoute
  '/devices': typeof DevicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-investigator': typeof AiInvestigatorRoute
  '/devices': typeof DevicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-investigator' | '/devices'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-investigator' | '/devices'
  id: '__root__' | '/' | '/ai-investigator' | '/devices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInvestigatorRoute: typeof AiInvestigatorRoute
  DevicesRoute: typeof DevicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-investigator': {
      id: '/ai-investigator'
      path: '/ai-investigator'
      fullPath: '/ai-investigator'
      preLoaderRoute: typeof AiInvestigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInvestigatorRoute: AiInvestigatorRoute,
  DevicesRoute: DevicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
